title: Venture
email: admin@venturecraftcoffee.com
description: >- # this means to ignore newlines until "baseurl:"
  Venture Craft Coffee
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://venturecraftcoffee.com" # the base hostname & protocol for your site, e.g. http://example.com
# Build settings
remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jekyll-feed
collections:
  menu:
    output: true